### ISSUE TITLE
Cannot get to work after SerialPort update

### ISSUE THREAD

**Issue by stormboy** [mozz100/node-xbee#2]
It may be the fault of node-serialport since release 1.0, but I cannot communicate with my XBees anymore.

**Comment by mozz100** [comment]
Glad to hear that others are using this stuff - sorry to hear that your XBees aren't talking to you!

ok, well, I used version 0.7.3 of serialport when I originally wrote this module, and I've updated the readme to show how to install this specific version.

https://github.com/mozz100/node-xbee/commit/dceb40794b2ee15ee183a87c809ec91da64e9942#L0L48

Try that and see if it really is the version of serialport that's causing your problem?

If you're still stuck, more info is required.  What are you trying to do, what code are you running, etc.

If you haven't already, I recommend you look at the progress that's been made by @jouz

He's taken this stuff a lot further, and in the interests of mutual benefit, I'll probably use his code next time I revisit this stuff (I've contributed one or two tiny patches to it!)

Take a look here: https://github.com/jouz/svd-xbee

**Comment by stormboy** [comment]
Thanks, that suggestion worked. I didn't know about the version option in npm until now.  Sorry about the minimal details, but it was hard to know where to start giving information, and it's turned out it may not be needed at this point.  There is definitely some incompatibility between this version of node-xbee and version 1.0 of serialport, however.

I did end up finding @jous 's work last night, and got it going.  That took an effort for me on Mac because I was using /dev/tty.usbserial-XXXXXXX not realising that /dev/cu.usbserial-XXXXXXXX existed and worked with serialport2. It's all fine using tty on Linux.

Thanks again for your response. Let the Zigbee fun continue.
