### ISSUE TITLE
Remote Control

### ISSUE THREAD

**Issue by PavilionSMV** [mozz100/node-xbee#4]
Hi,
Thanks for sharing that useful library.
I use it to receive data from a xbee and works great.  Now I want to control a remote LED. I have a coordinator in API mode and a Router in AT. But I haven't  been able to operate it.

For example to turn on D0 --- 0x05
          turn off D0 ---0x04

var rsp = require("serialport");
var xbee = require("./xbee");
var SerialPort = rsp.SerialPort; 

var serial_xbee = new SerialPort("/dev/ttyUSB0", { 
  parser: xbee.packetParser()
});

var remote64 = [0x00,0x13,0xa2,0x00,0x40,0x91,0x9c,0x4d]; //Router ID
var remote16 =  [0xff, 0xfe]; 

function RemoteAT(cmd, val, remote64, remote16) {
  var atc = new xbee.RemoteATCommand();
  atc.setCommand(cmd);
  atc.commandParameter = val;
  atc.destination64 = remote64;
  atc.destination16 = remote16;
  b = atc.getBytes();
  serial_xbee.write(b);
  //console.log('Wrote bytes to serial port', b);
}

RemoteAT('D0', 0x05, remote64, remote16);

Thanks

**Comment by mozz100** [comment]
If you haven't got too far into this, you should check out https://github.com/jouz/svd-xbee

jouz has taken what I started and built upon it. When I start a new project, I start from there.

Nevertheless, I think you will be ok if you wrap your value as an array of one member.  Like this:

```
RemoteAT('D0', [0x05], remote64, remote16);
```

**Comment by PavilionSMV** [comment]
an array!!! that was the problem, thank you very much :)
