### ISSUE TITLE
(node) sys is deprecated. Use util instead.

### ISSUE THREAD

**Issue by hitswa** [mozz100/node-xbee#6]
Hay I am getting this error while trying your code...

```
(node) sys is deprecated. Use util instead.
DEPRECATION: Please use `require('serialport')` instead of `require('serialport').SerialPort
events.js:141
      throw er; // Unhandled 'error' event
```

Have some solution?

**Comment by mozz100** [comment]
It sounds like you are using a version of nodejs that didn't exist when this code was written?

More generally, though, I haven't looked at the code here for a long time, and I don't anticipate being able to any time soon.  Others have taken it, built on it and made newer and better libraries.

I wouldn't start a new project using this code.  Instead, as linked in the README, please look at https://github.com/jankolkmeier/xbee-api
